### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by Gyarik** [gabrielrovesti/Calcolo-numerico-UniPD#1]
Ho capito che è open source ma porca miseria mi hai freebootato

![image](https://user-images.githubusercontent.com/40033289/163063434-f12e5297-2e3f-4d3e-87fa-165b9533c56b.png)

**Comment by gabrielrovesti** [comment]
Me lo sono salvato con lo scopo di modificarmelo, hai ragione, mi ero anche
dimenticato che caricandolo su GitHub c'era il tuo pezzo. Tolgo subito.
A volte sono un coglione... Grazie mille va là

Il mer 13 apr 2022, 00:13 Gyarik ***@***.***> ha scritto:
